// <auto-generated />
using System;
using FintaChartsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FintaChartsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250705140113_AddedInstrumantPricesTable")]
    partial class AddedInstrumantPricesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FintaChartsApi.Models.Data.Instrument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("BaseCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Currency")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("TickSize")
                        .HasColumnType("numeric(18, 9)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.InstrumentPrice", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProviderId")
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Ask")
                        .HasColumnType("numeric(18, 8)");

                    b.Property<decimal?>("Bid")
                        .HasColumnType("numeric(18, 8)");

                    b.Property<decimal?>("Last")
                        .HasColumnType("numeric(18, 8)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("InstrumentId", "ProviderId");

                    b.HasIndex("ProviderId");

                    b.ToTable("InstrumentPrices");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.Provider", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.InstrumentPrice", b =>
                {
                    b.HasOne("FintaChartsApi.Models.Data.Instrument", "Instrument")
                        .WithMany("Prices")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FintaChartsApi.Models.Data.Provider", "Provider")
                        .WithMany("Prices")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.Instrument", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.Provider", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
