// <auto-generated />
using System;
using FintaChartsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FintaChartsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FintaChartsApi.Models.Data.Bar", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime>("T")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("C")
                        .HasColumnType("numeric(18, 9)");

                    b.Property<decimal>("H")
                        .HasColumnType("numeric(18, 9)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("L")
                        .HasColumnType("numeric(18, 9)");

                    b.Property<decimal>("O")
                        .HasColumnType("numeric(18, 9)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderId1")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("V")
                        .HasColumnType("numeric(18, 9)");

                    b.HasKey("InstrumentId", "Resolution", "T");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProviderId1");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.Instrument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("BaseCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Currency")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Exchange")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("TickSize")
                        .HasColumnType("numeric(18, 9)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.Provider", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.Bar", b =>
                {
                    b.HasOne("FintaChartsApi.Models.Data.Instrument", "Instrument")
                        .WithMany("Bars")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FintaChartsApi.Models.Data.Provider", null)
                        .WithMany("Bars")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FintaChartsApi.Models.Data.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.Instrument", b =>
                {
                    b.Navigation("Bars");
                });

            modelBuilder.Entity("FintaChartsApi.Models.Data.Provider", b =>
                {
                    b.Navigation("Bars");
                });
#pragma warning restore 612, 618
        }
    }
}
