// <auto-generated />
using System;
using FintaChartsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FintaChartsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250704153406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FintaChartsApi.Models.Data.Bar", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime>("T")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("C")
                        .HasColumnType("numeric(18, 9)");

                    b.Property<decimal>("H")
                        .HasColumnType("numeric(18, 9)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("L")
                        .HasColumnType("numeric(18, 9)");

                    b.Property<decimal>("O")
                        .HasColumnType("numeric(18, 9)");

                    b.Property<decimal>("V")
                        .HasColumnType("numeric(18, 9)");

                    b.HasKey("InstrumentId", "Resolution", "T");

                    b.ToTable("Bars");
                });
#pragma warning restore 612, 618
        }
    }
}
